  build-windows-x86:
    name: Build ARM64 QEMU on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSYS2 and install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-pixman
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-ninja
            git
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-ncurses
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-gettext-runtime

      - name: Configure & Build (Windows)
        shell: msys2 {0}
        run: |
          rm -rf build-windows-x86
          mkdir build-windows-x86 && cd build-windows-x86
          ../configure --target-list=aarch64-softmmu --prefix=$PWD/install
          make -j$(nproc)
          make install

      - name: Clone msys2‑bundledlls helper
        shell: msys2 {0}
        run: git clone https://github.com/rollerozxa/msys2-bundledlls.git  

      - name: Bundle all runtime DLLs
        shell: msys2 {0}
        run: |
          ./bundledlls.sh \
            build-windows-x86/install/qemu-system-aarch64.exe \
            build-windows-x86/install/

      - name: Upload ARM64 build for Windows
        uses: actions/upload-artifact@v4
        with:
          name: qemu-windows-x86_arm64
          path: build-windows-x86/install/**
